<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201126123841 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        $this->addSql('CREATE TABLE test (
                                id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                foo VARCHAR(255) DEFAULT NULL, 
                                bar VARCHAR(255) DEFAULT NULL
                                )');
    }

    public function down(Schema $schema) : void
    {
        $this->addSql('DROP TABLE test');
    }
}
