#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{?name}
    controller: App\Controller\ConferenceController::index





## TESTS  ##

test:
    path: /test/{name}
    controller: App\Controller\TestController::actionTest
