#index:
#    path: /
#    controller: App\Controller\ConferenceController::index

## Conference ##

homepage:
    path: /
    controller: App\Controller\ConferenceController::index

conference/show-one:
    path: /conference/show-one/{conference}
    controller: App\Controller\ConferenceController::showOne





## TESTS  ##

test:
    path: /test/{name}
    controller: App\Controller\TestController::actionTest
