#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{name}
    controller: App\Controller\ConferenceController::index





## TESTS  ##

test_1:
    path: /test/{name}
    controller: App\Controller\TestController::actionTest
